## This workflow runs on all pull requests and issues.
## It greets new contributors when they create their first issue or open their first pull request.
##
## More details on https://github.com/actions/first-interaction

name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello ${{ github.actor }}! Thanks for opening your first issue in this repository! We will get back to you as soon as possible."
        pr-message: "Hello ${{ github.actor }}"
